trigger: 
- main
pool:
 name: UbuntuVM
variables:
 buildConfiguration: 'Release'
steps:
- task: UseDotNet@2
  displayName: "Use .Net SDK 6.x"
  inputs:
    packageType: sdk
    version: '6.x'
  

