trigger: 
- main
pool:
 name: UbuntuVM
variables:
 buildConfiguration: 'Release'
steps:
- script: echo "Hello Word $(buildConfiguration)"
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet build --configuration $(buildConfiguration) **/*.csproj