trigger: 
- main
pool:
 name: UbuntuVM
variables:
 buildConfiguration: 'Release'
steps:
  
- script: echo "$(dotnet --version)"
  displayName: 'Print out dotnet sdk version'
  
- script: dotnet build --configuration $(buildConfiguration) **/*.csproj
  displayName: 'dotnet build $(buildConfiguration)'